# docker-compose.yml (sin credenciales)
version: '3.8'

services:
  backend:
    build: ./Server
    container_name: bambina-backend
    ports:
      - "3001:3001"
    env_file:
      - .env.backend  
    volumes:
      - ./Server:/app
      - /app/node_modules
    networks:
      - bambina-net

  frontend:
    build: ./Client
    container_name: bambina-frontend
    ports:
      - "5173:5173"
    env_file:
      - .env.frontend  
    depends_on:
      - backend
    networks:
      - bambina-net

networks:
  bambina-net:
    driver: bridge